version: '3.9'

services:
  postgres:
    restart: unless-stopped
    image: postgres:16
    container_name: lapis
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/lapis
    logging:
      driver: json-file
      options:
        max-size: '200k'
        max-file: '10'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  postgres_data:
